# Generated by Django 2.2.3 on 2019-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='brand',
            field=models.CharField(default='', max_length=10),
        ),
    ]
