# Generated by Django 2.2.3 on 2019-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=10)),
                ('brand', models.IntegerField(max_length=10)),
            ],
        ),
    ]
